services:
  app:
    build: .
    container_name: delivery-api
    command: sh -c "yarn install && npx nest start --watch"
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: delivery
      DB_PASSWORD: delivery123
      DB_DATABASE: delivery_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: dev-secret-change-in-production
      JWT_EXPIRATION: 7d
      PORT: 3000
      RESEND_API_KEY: re_fLvy9LTQ_PWEdzcqWyNwajCqEXY3wiQGw
      MAIL_FROM: BCM TECH DELIVERY <noreply@bcmtech.com.br>
      CLOUDINARY_CLOUD_NAME: dgbavxge6
      CLOUDINARY_API_KEY: 279355333423469
      CLOUDINARY_API_SECRET: lILGnp653qtQQmOGV0uQVDn4Uew
      PAGARME_SECRET_KEY: sk_test_6f0b7122384f431faa8b0c6b19463425
      PAGARME_PUBLIC_KEY: pk_test_aMzdnWyuDCykrpN2
      PAGARME_PLATFORM_RECIPIENT_ID: re_cmmutgjxn00d20l9tbqyidmmf
      APP_URL: http://localhost:3000
      VENDOR_APP_URL: http://localhost:3001
      SERPAPI_KEY: a0e65ca2095765511a9001e46e1eaeba5fdc0c5d40dc4c156f7097f59c3e0521
      GOOGLE_CLIENT_ID: 194367338134-2svkdsl9amt5qfihsqabt438l2sj1pj8.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      WAHA_API_URL: http://18.231.9.158
      WAHA_API_KEY: bcmtech-waha-2026-key
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    container_name: delivery-postgres
    environment:
      POSTGRES_USER: delivery
      POSTGRES_PASSWORD: delivery123
      POSTGRES_DB: delivery_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: delivery-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
