import { registerEnumType } from '@nestjs/graphql';

export enum OrderStatus {
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  PAYMENT_REVIEW = 'PAYMENT_REVIEW',
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  PREPARING = 'PREPARING',
  READY = 'READY',
  VENDOR_CONFIRMED_PICKUP = 'VENDOR_CONFIRMED_PICKUP',
  PICKED_UP = 'PICKED_UP',
  DELIVERING = 'DELIVERING',
  DELIVERER_CONFIRMED_DELIVERY = 'DELIVERER_CONFIRMED_DELIVERY',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  DISPUTED = 'DISPUTED',
}

registerEnumType(OrderStatus, { name: 'OrderStatus' });
